export { routes } from "./routes";
export { default as Nav } from "./Components/Nav";
export { default as Footer } from "./Components/Footer";
export { useCartContext } from "./Components/cartcontext/CartContextProvider";
export { default as CartContextProvider } from "./Components/cartcontext/CartContextProvider";
export { allImg } from "./data";
export { default as Breadcrumb } from "./Components/Breadcrumb";
export { type ProductItems } from "./types/typeCartContext";
export { formatNumberWithCommas } from "./utils/numberSeparator";
export { default as Providers } from "./Components/Providers";